all test passed

diff --git a/npc/Sim/Makefile b/npc/Sim/Makefile
--- a/npc/Sim/Makefile
+++ b/npc/Sim/Makefile
@@ -8,7 +8,7 @@ BUILD_DIR = build
 # 条件编译选项
 DIFFTEST ?= 1  # 默认启用差分测试
 MTRACE ?= 1    # 默认禁用内存跟踪
-#ITRACE ?= 0    # 默认禁用指令跟踪
+ITRACE ?= 1    # 默认禁用指令跟踪
 
 # 初始化基础CPPFLAGS
 CPPFLAGS = -I$(VERILATOR_ROOT)/include \
@@ -59,7 +59,7 @@ $(BUILD_DIR)/%.o: %.cpp
 
 run: main
 	$(call git_commit, "run npc sim") # DO NOT REMOVE THIS LINE!!
-	LD_PRELOAD=/usr/lib64/libasan.so.8 ./main --diff ../../nemu/build/riscv32-nemu-interpreter-so  -m #TestBin/crc32-riscv32e-npc.bin
+	LD_PRELOAD=/usr/lib64/libasan.so.8 ./main --diff /home/sealessland/ysyx-workbench/nemu/build/riscv32-nemu-interpreter-so   -m TestBin/div-riscv32e-npc.bin
 run_nodiff: main
 	$(call git_commit, "run npc sim without difftest") # DO NOT REMOVE THIS LINE!!
 	LD_PRELOAD=/usr/lib64/libasan.so.8 ./main
@@ -71,3 +71,19 @@ clean:
 debug: main
 	$(call git_commit, "debug npc sim") # DO NOT REMOVE THIS LINE!!
 	gdb ./main
+commit:
+	$(call git_commit, "commit npc sim") # DO NOT REMOVE THIS LINE!!
+
+runall: main
+	$(call git_commit, "run npc sim") # DO NOT REMOVE THIS LINE!!
+	@for test_bin in $(wildcard TestBin/*-npc.bin); do \
+		echo "===================================================="; \
+		echo "Running test: $$test_bin"; \
+		echo "===================================================="; \
+		LD_PRELOAD=/usr/lib64/libasan.so.8 ./main --diff ../../nemu/build/riscv32-nemu-interpreter-so -nd -m $$test_bin; \
+		if [ $$? -ne 0 ]; then \
+			echo "Test $$test_bin FAILED!"; \
+			exit 1; \
+		fi \
+	done
+	@echo "All tests passed successfully!"
